# Generated by Django 4.2.2 on 2023-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
